---
title: "My English Activity Log : MEAL"
author:
  - name: "Willems Cyril" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---

What I've done in English during this year:

* I love playing videogames especially online and i got a particular game where i spend many hours. this is a team game    (we are five versus five) and the key of the victory is the communication between the member of the team. 
  How are we communicating ?  We can talk in-game, in other words we press a button then we talk and all the members of    the team can hear me. We are rarely french so we must speak in english to be understand.
  
* I watch lot's of youtube's video in english every day before going to my bed.

* Recently i've watch the witcher and game of thrones in english. the second was pretty difficult and take me a lot of     time (eight season) but i've already seen it in french. I have also see some movie in English but not many.

* I order sometimes at a restaurant where the waiters are irish and whodon't speak english.
